name: openwrt-X86-64-mod-cl

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  #schedule:
  #  - cron: 0 0 * * *
  
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: 开始工作了
      uses: actions/checkout@master
    
    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo swapoff /swapfile
        sudo rm -f /swapfile
        sudo -E apt-get update
        sudo -E apt-get upgrade
        sudo -E apt-get -y install build-essential antlr3 gperf asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib linux-libc-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        
    - name: 拉取最新源码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
    
    - name: 添加删除插件
      run: |
        # 添加第三方插件
        cd openwrt
        git clone https://github.com/chenhw2/openwrt-dnsmasq-extra.git package/feeds/openwrt-dnsmasq-extra
        sed -i '4a src-git lienol https://github.com/Lienol/openwrt-package' feeds.conf.default
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate
   
    - name: 更新源
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    
    - name: 创建配置文件 - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64-mod.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt && make defconfig
        
    - name: 下载固件包(Download package)
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)  V=s
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    - name: 编译固件(多线程)
      working-directory: ./openwrt
      run: |
        make -j$(nproc) V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin
        echo "::set-output name=status::success"
 
    - name: 打包文件
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
        
    - name: 上传固件目录
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware_X86-64-mod
        path: ${{ env.FIRMWARE }}
